-- Gold: the reporting table the dashboard reads.
CREATE OR ALTER TABLE GOLD.WEEKLY_ACTIVE_USERS (
    WEEK_START DATE NOT NULL,
    CONTENT_AREA VARCHAR NOT NULL,
    ACTIVE_USERS NUMBER NOT NULL,
    RULES_VERSION VARCHAR NOT NULL,
    REFRESHED_AT TIMESTAMP_LTZ NOT NULL
);

CREATE OR REPLACE PROCEDURE GOLD.BUILD_WEEKLY_ACTIVE_USERS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    INSERT OVERWRITE INTO GOLD.WEEKLY_ACTIVE_USERS
    SELECT DATE_TRUNC('WEEK', EVENT_TIME)::DATE, CONTENT_AREA, COUNT(DISTINCT USER_ID),
           MAX(RULES_VERSION), CURRENT_TIMESTAMP()
    FROM SILVER.EVENTS
    WHERE CONTENT_AREA IS NOT NULL
    GROUP BY 1, 2;
    RETURN 'Gold weekly active users rebuilt';
END;
$$;
