-- Append-only audit trail: one row per successful deployment to this environment.
CREATE TABLE IF NOT EXISTS OPS.DEPLOY_LOG (
    ENVIRONMENT VARCHAR NOT NULL,
    COMMIT_SHA VARCHAR NOT NULL,
    DEPLOYED_BY VARCHAR NOT NULL,
    DEPLOYED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
