--!jinja
-- Readers see Gold and the dashboard only. Runs last because CREATE OR REPLACE drops object grants.
GRANT USAGE ON DATABASE ANALYTICS_{{ env }} TO ROLE ANALYTICS_READER_{{ env }};
GRANT USAGE ON SCHEMA GOLD TO ROLE ANALYTICS_READER_{{ env }};
GRANT SELECT ON ALL TABLES IN SCHEMA GOLD TO ROLE ANALYTICS_READER_{{ env }};
GRANT USAGE ON STREAMLIT GOLD.ENGAGEMENT_DASHBOARD TO ROLE ANALYTICS_READER_{{ env }};
