-- Bronze: source events exactly as delivered, plus the load time.
-- In a real account the ingestion tool writes Bronze directly and this load step is not needed.
CREATE OR ALTER TABLE BRONZE.AMPLITUDE_EVENTS (
    EVENT_ID VARCHAR,
    USER_ID VARCHAR,
    EVENT_TIME TIMESTAMP_NTZ,
    EVENT_TYPE VARCHAR,
    CONTENT_AREA VARCHAR,
    PLATFORM VARCHAR,
    USER_TYPE VARCHAR,
    LOADED_AT TIMESTAMP_LTZ NOT NULL
);

CREATE OR REPLACE PROCEDURE BRONZE.LOAD_AMPLITUDE_EVENTS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    INSERT OVERWRITE INTO BRONZE.AMPLITUDE_EVENTS
    SELECT EVENT_ID, USER_ID, EVENT_TIME, EVENT_TYPE, CONTENT_AREA, PLATFORM, USER_TYPE, CURRENT_TIMESTAMP()
    FROM LANDING.AMPLITUDE.EVENTS;
    RETURN 'Bronze events loaded';
END;
$$;
