-- Silver: one clean, deduplicated row per event. Business rules live here.
CREATE OR ALTER TABLE SILVER.EVENTS (
    EVENT_ID VARCHAR NOT NULL,
    USER_ID VARCHAR NOT NULL,
    EVENT_TIME TIMESTAMP_NTZ NOT NULL,
    EVENT_TYPE VARCHAR,
    CONTENT_AREA VARCHAR,
    PLATFORM VARCHAR,
    USER_TYPE VARCHAR,
    RULES_VERSION VARCHAR NOT NULL
);

CREATE OR REPLACE PROCEDURE SILVER.BUILD_EVENTS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    INSERT OVERWRITE INTO SILVER.EVENTS
    SELECT EVENT_ID, USER_ID, EVENT_TIME, EVENT_TYPE,
           LOWER(TRIM(CONTENT_AREA)), LOWER(PLATFORM), LOWER(USER_TYPE),
           'v1' AS RULES_VERSION
    FROM BRONZE.AMPLITUDE_EVENTS
    WHERE EVENT_ID IS NOT NULL
      AND USER_ID IS NOT NULL
      AND EVENT_TIME IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY EVENT_ID ORDER BY LOADED_AT DESC) = 1;
    RETURN 'Silver events rebuilt with v1 rules';
END;
$$;
