-- Read-only audit and cost queries. SYSADMIN inherits every environment role.
USE ROLE SYSADMIN;
USE WAREHOUSE REPORTING_WH;

-- 1. What is deployed where, from which commit, by whom.
SELECT * FROM ANALYTICS_DEV.OPS.DEPLOY_LOG
UNION ALL SELECT * FROM ANALYTICS_QA.OPS.DEPLOY_LOG
UNION ALL SELECT * FROM ANALYTICS_PRD.OPS.DEPLOY_LOG
ORDER BY DEPLOYED_AT DESC;

-- 2. The numbers each environment shows right now.
--    v1: parents 3, educators 2.   v2: parents 2, educators 1.
SELECT 'DEV' AS ENVIRONMENT, CONTENT_AREA, ACTIVE_USERS, RULES_VERSION FROM ANALYTICS_DEV.GOLD.WEEKLY_ACTIVE_USERS
UNION ALL SELECT 'QA', CONTENT_AREA, ACTIVE_USERS, RULES_VERSION FROM ANALYTICS_QA.GOLD.WEEKLY_ACTIVE_USERS
UNION ALL SELECT 'PRD', CONTENT_AREA, ACTIVE_USERS, RULES_VERSION FROM ANALYTICS_PRD.GOLD.WEEKLY_ACTIVE_USERS
ORDER BY CONTENT_AREA, ENVIRONMENT;

-- 3. The task graph: definitions, schedule state and recent runs.
--    PRD's root is "started" (on schedule); DEV and QA roots stay "suspended".
SHOW TASKS IN SCHEMA ANALYTICS_PRD.OPS;
SELECT ROOT_TASK_NAME, STATE, SCHEDULED_TIME, COMPLETED_TIME, FIRST_ERROR_MESSAGE
FROM TABLE(ANALYTICS_PRD.INFORMATION_SCHEMA.COMPLETE_TASK_GRAPHS(
    RESULT_LIMIT => 20, ROOT_TASK_NAME => 'PIPELINE_ROOT'))
ORDER BY SCHEDULED_TIME DESC;

-- 4. The live definition next to the file in Git.
SELECT GET_DDL('PROCEDURE', 'ANALYTICS_PRD.SILVER.BUILD_EVENTS()') AS LIVE_DEFINITION;
LS @PLATFORM.GIT.ANALYTICS_REPO/branches/main/pipelines/;

-- 5. Every statement a deployment ran, found by its query tag.
--    ACCOUNT_USAGE can lag by up to about 45 minutes.
SELECT QUERY_TAG, START_TIME, USER_NAME, ROLE_NAME, QUERY_TYPE, EXECUTION_STATUS,
       LEFT(QUERY_TEXT, 120) AS QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE QUERY_TAG LIKE 'deploy:%'
  AND START_TIME > DATEADD('day', -7, CURRENT_TIMESTAMP())
ORDER BY START_TIME DESC;

-- 6. What deployments, pipelines and dashboards cost.
SHOW RESOURCE MONITORS LIKE 'ANALYTICS_MONTHLY_BUDGET';
SELECT WAREHOUSE_NAME, START_TIME::DATE AS DAY, ROUND(SUM(CREDITS_USED), 4) AS CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE WAREHOUSE_NAME IN ('PIPELINE_WH', 'REPORTING_WH')
  AND START_TIME > DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY 1, 2
ORDER BY 2 DESC, 1;
